mode: "local"
db:
  local_storage_path: "./storage/sso.sqlite3"
  db_name: "sso"
grpc:
  grpc_addr: "127.0.0.1"
  grpc_port: 8088
  grpc_timeout: "5s"
tokenTTL: "1h"
refreshTokenTTL: "168h"
redis:
  redis_addr: "127.0.0.1:6379"
  password: ""
  user: ""
  db: 0
  max_retries: 3
  retry_delay: "5s"
  dial_timeout: "10s"
  timeout: "5s"
  tokenTTL: "1h"
api_server:
  api_addr: "127.0.0.1"
  api_port: "8089"
