mode: "local"
db:
  storage_path: "./storage/sso.sqlite3"
grpc:
  url: "127.0.0.1"
  port: 8088
  timeout: 5s
tokenTTL: 1h
refreshTokenTTL: 7d
redis:
    addr: "127.0.0.1:6379"
    password: ""
    user: ""
    db: 0
    max_retries: 5
    dial_timeout: 10s
    timeout: 5s
    tokenTTL: 1h