mode: "local"
db:
  storage_path: "./storage/sso.sqlite3"
grpc:
  url: "127.0.0.1"
  port: 8088
  timeout: 5s
tokenTTL: 1h
redis:
    addr: 127.0.0.1
    password: ""
    user: ""
    db: 0
    maxretries: 5
    dialtimeout: 10
    timeout: 5